apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-datanode-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.datanode.volume.storage }}