apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.datanode.name }}
  name: {{ .Values.datanode.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.datanode.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.datanode.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.datanode.name }}
    spec:
      hostname: {{ .Values.datanode.hostname }}
      restartPolicy: Always
      volumes:
      - name: graylog-datanode
        persistentVolumeClaim:
          claimName: graylog-datanode-pvc
      initContainers:
      - name: "wait-for-{{ .Values.mongodb.name }}"
        image: busybox
        command: ["sh", "-c", "until nc -z {{ .Values.mongodb.Service.name }} 27017; do echo Waiting for {{ .Values.mongodb.name }} availability; sleep 1; done;"]
      containers:
      - image: "{{ .Values.datanode.image.name }}:{{ .Values.datanode.image.tag }}"
        name: graylog-datanode
        env:
        - name: GRAYLOG_DATANODE_NODE_ID_FILE
          value: "/var/lib/graylog-datanode/node-id"
        - name: GRAYLOG_DATANODE_MONGODB_URI
          value: "mongodb://{{ .Values.mongodb.Service.name }}:27017/graylog"
        - name: GRAYLOG_DATANODE_PASSWORD_SECRET
          valueFrom:
            secretKeyRef:
              name: graylog-password-secret
              key: GRAYLOG_PASSWORD_SECRET
        ports:
        - containerPort: 8999
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - mountPath: /var/lib/graylog-datanode
          name: graylog-datanode
        resources:
          requests:
            memory: {{ .Values.datanode.containerResources.memory.requests | quote }}
          limits:
            memory: {{ .Values.datanode.containerResources.memory.limits | quote }}
status: {}