apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.graylog.volume.storage }}