apiVersion: v1
data:
  GRAYLOG_PASSWORD_SHA256: {{ .Values.graylogRootPasswordSHA256 | b64enc | quote }}
kind: Secret
metadata:
  name: graylog-root-password-sha256
  namespace: {{ .Values.namespace }}
