apiVersion: v1
data:
  GRAYLOG_PASSWORD_SECRET: {{ .Values.graylogPasswordSecret | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: graylog-password-secret
  namespace: {{ .Values.namespace }}
