apiVersion: v1
kind: Service
metadata:
  name: "headless-{{ .Values.mongodb.Service.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: {{ .Values.mongodb.name }}