# Graylog values file

namespace: graylog







mongodb:
  
  # Name of StatfulSet
  name: mongodb

  # Name and tag of the image, officialy supported with mongo:8.0
  image:
    name: mongo
    tag: 8.0

  # Num of replicas for the mongodb StatefulSet
  replicas: 1

  # Hostname of the container in the StatefulSet
  hostname: mongodb

  # mongodb StatefulSet PVC values

  volumes:
    # Size for the mongodb-data volume
    mongodb-data:
      storageSize: 4Gi # Default fits for a small lab

    # Size for the mongodb-data volume
    mongodb-config:
      storageSize: 4Gi # Default fits for a small lab

  # Values of the mongodb Service
  Service:

    # Name of the service
    name: mongodb
    nodePort: 32017